master_data_loading:
  csv_file_path: "../data/train/df_master.csv"
  project_id: "mineral-rune-450809-a4"
  dataset_id: "ecommerce_master_dataset"
  table_id: "masterdata"
  bigquery_location: "EU"  
cloud_logging:
  log_name: "bigquery-loader"